--- Day 9: Movie Theater ---
You slide down the firepole in the corner of the playground and land in the North Pole base movie theater!

The movie theater has a big tile floor with an interesting pattern. Elves here are redecorating the theater by switching out some of the square tiles in the big grid they form. Some of the tiles are red; the Elves would like to find the largest rectangle that uses red tiles for two of its opposite corners. They even have a list of where the red tiles are located in the grid (your puzzle input).


In [1]:
elf_data = []

with open('day09.txt', 'r') as file:
    for line in file:
        elf_data.append(line.replace("\n", ""))

for i in range(len(elf_data)):
    elf_data[i] = elf_data[i].split(',')
print(len(elf_data))
print(elf_data[0:10])
print(type(elf_data))


496
[['98220', '50383'], ['98220', '51611'], ['98394', '51611'], ['98394', '52815'], ['97964', '52815'], ['97964', '54005'], ['97594', '54005'], ['97594', '55224'], ['97608', '55224'], ['97608', '56483']]
<class 'list'>



For example:

7,1
11,1
11,7
9,7
9,5
2,5
2,3
7,3
Showing red tiles as # and other tiles as ., the above arrangement of red tiles would look like this:

..............
.......#...#..
..............
..#....#......
..............
..#......#....
..............
.........#.#..
..............
You can choose any two red tiles as the opposite corners of your rectangle; your goal is to find the largest rectangle possible.

For example, you could make a rectangle (shown as O) with an area of 24 between 2,5 and 9,7:

..............
.......#...#..
..............
..#....#......
..............
..OOOOOOOO....
..OOOOOOOO....
..OOOOOOOO.#..
..............
Or, you could make a rectangle with area 35 between 7,1 and 11,7:

..............
.......OOOOO..
.......OOOOO..
..#....OOOOO..
.......OOOOO..
..#....OOOOO..
.......OOOOO..
.......OOOOO..
..............
You could even make a thin rectangle with an area of only 6 between 7,3 and 2,3:

..............
.......#...#..
..............
..OOOOOO......
..............
..#......#....
..............
.........#.#..
..............
Ultimately, the largest rectangle you can make in this example has area 50. One way to do this is between 2,5 and 11,1:

..............
..OOOOOOOOOO..
..OOOOOOOOOO..
..OOOOOOOOOO..
..OOOOOOOOOO..
..OOOOOOOOOO..
..............
.........#.#..
..............

In [2]:
test_data = []

with open('test.txt', 'r') as file:
    for line in file:
        test_data.append(line.replace("\n", ""))

for i in range(len(test_data)):
    test_data[i] = test_data[i].split(',')
print(len(test_data))
print(test_data)
print(type(test_data))


8
[['7', '1'], ['11', '1'], ['11', '7'], ['9', '7'], ['9', '5'], ['2', '5'], ['2', '3'], ['7', '3']]
<class 'list'>


In [3]:
import numpy as np

In [6]:
def find_largest_area(data):
    area = 0
    area = locate_furthest_apart(data)
    return area

def locate_furthest_apart(data):
    distances = np.zeros((len(data), len(data)))
    for i in range(0, len(data)):
        for j in range(i+1, len(data)):
            distances[i][j] = calc_difference(data[i], data[j])
            distances[j][i] = distances[i][j]
            print(i, j, data[i], data[j], distances[i][j])

    print(distances)
    return np.max(distances)

def calc_difference(i, j):
    corner0x = int(i[0])
    corner1x = int(j[0])
    corner0y = int(i[1])
    corner1y = int(j[1])
    return (abs(corner0x-corner1x)+1) * (abs(corner0y-corner1y)+1)

find_largest_area(test_data)    

0 1 ['7', '1'] ['11', '1'] 5.0
0 2 ['7', '1'] ['11', '7'] 35.0
0 3 ['7', '1'] ['9', '7'] 21.0
0 4 ['7', '1'] ['9', '5'] 15.0
0 5 ['7', '1'] ['2', '5'] 30.0
0 6 ['7', '1'] ['2', '3'] 18.0
0 7 ['7', '1'] ['7', '3'] 3.0
1 2 ['11', '1'] ['11', '7'] 7.0
1 3 ['11', '1'] ['9', '7'] 21.0
1 4 ['11', '1'] ['9', '5'] 15.0
1 5 ['11', '1'] ['2', '5'] 50.0
1 6 ['11', '1'] ['2', '3'] 30.0
1 7 ['11', '1'] ['7', '3'] 15.0
2 3 ['11', '7'] ['9', '7'] 3.0
2 4 ['11', '7'] ['9', '5'] 9.0
2 5 ['11', '7'] ['2', '5'] 30.0
2 6 ['11', '7'] ['2', '3'] 50.0
2 7 ['11', '7'] ['7', '3'] 25.0
3 4 ['9', '7'] ['9', '5'] 3.0
3 5 ['9', '7'] ['2', '5'] 24.0
3 6 ['9', '7'] ['2', '3'] 40.0
3 7 ['9', '7'] ['7', '3'] 15.0
4 5 ['9', '5'] ['2', '5'] 8.0
4 6 ['9', '5'] ['2', '3'] 24.0
4 7 ['9', '5'] ['7', '3'] 9.0
5 6 ['2', '5'] ['2', '3'] 3.0
5 7 ['2', '5'] ['7', '3'] 18.0
6 7 ['2', '3'] ['7', '3'] 6.0
[[ 0.  5. 35. 21. 15. 30. 18.  3.]
 [ 5.  0.  7. 21. 15. 50. 30. 15.]
 [35.  7.  0.  3.  9. 30. 50. 25.]
 [21. 21.  3.  0.  3. 2

50.0


Using two red tiles as opposite corners, what is the largest area of any rectangle you can make?


In [ ]:
find_largest_area(elf_data)